
Ttree:

  SwissConfederation:
    WebStarter:
      dummyContent:
        navigation: 'https://raw.githubusercontent.com/liip/bund_drupal_starterkit_dummycontent/master/data/navigation_menu_item.csv'

      navigation:
        service:
          startingPoint: '#c142ef64-ea36-423a-8a2a-c581812f5316'

  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: 'Ttree.SwissConfederation.WebStarter:Default.Document'

Neos:

  Neos:
    userInterface:
      translation:
            autoInclude:
              Ttree.SwissConfederation.WebStarter:
                - 'NodeTypes/*'
      navigateComponent:
        nodeTree:
          loadingDepth: 1

  ContentRepository:
    contentDimensions:
      language:
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: icon-language
        default: fr
        defaultPreset: fr
        presets:
          all: null
          fr:
            label: FR
            values:
              - fr
            uriSegment: fr
          de:
            label: DE
            values:
              - de
              - fr
            uriSegment: de
          it:
            label: IT
            values:
              - it
              - de
              - fr
            uriSegment: it
          rm:
            label: RM
            values:
              - rm
              - de
              - fr
              - it
            uriSegment: rm
          en:
            label: EN
            values:
              - en
              - de
              - fr
              - it
            uriSegment: en
