
Ttree:
  SwissConfederation:
    WebStarter:
      navigation:
        service:
          startingPoint: '#c142ef64-ea36-423a-8a2a-c581812f5316'
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: 'Ttree.SwissConfederation.WebStarter:Default.Document'
Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: icon-language
        default: fr
        defaultPreset: fr
        presets:
          all: null
          fr:
            label: French
            values:
              - fr
            uriSegment: fr
          de:
            label: German
            values:
              - de
              - fr
            uriSegment: de
          it:
            label: Italian
            values:
              - it
              - de
              - fr
            uriSegment: it
          rm:
            label: Romansh
            values:
              - rm
              - de
              - fr
              - it
            uriSegment: rm
          en:
            label: English
            values:
              - en
              - de
              - fr
              - it
            uriSegment: en
